### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [snacsnoc/fbpkg#3]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by snacsnoc** [comment]
Hi codehangen,
Yes the project is still active. I am working on updating [SnackLinux](https://github.com/snacsnoc/snacklinux) and slowly working my way to this project.
I welcome any pull requests

**Comment by ghost** [comment]
Hi snacsnoc.

> Hi codehangen,
> Yes the project is still active. I am working on updating [SnackLinux](https://github.com/snacsnoc/snacklinux) and slowly working my way to this project.
> I welcome any pull requests

thank you for feedback. I am happy with your message and want to contribute something.
